name:                bitfix
version:             0.1.0.0
github:              "githubuser/bitfix"
license:             BSD3
author:              "TogoorooDev"
maintainer:          "hens25252@protonmail.com"
copyright:           "2022 TogoorooDev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bitfix#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- req
- bytestring

library:
  source-dirs: src

executables:
  bitfix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitfix

tests:
  bitfix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitfix
